/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  mySidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'category',
      label: 'Introduction',
      items: [
        {
          type: 'doc',
          id: 'Introduction/installation',
        },
        {
          type: 'doc',
          id: 'Introduction/community',
        },
        {
          type: 'doc',
          id: 'Introduction/what-is-komiser',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'category',
          label: 'How to Komiser',
          items: [
            {
              type: 'doc',
              id: 'Guides/How to Komiser/overview',
            },
            {
              type: 'doc',
              id: 'Guides/How to Komiser/how-to-s3',
            },
            {
              type: 'doc',
              id: 'Guides/How to Komiser/how-to-ec2',
            },
            {
              type: 'doc',
              id: 'Guides/How to Komiser/alerts',
            },
          ]
        },
        {
          type: 'category',
          label: 'Cloud Cost Savings Tips',
          items: [
            {
              type: 'doc',
              id: 'Guides/Cloud Cost Savings Series/overview',
            },
            {
            type: 'category',
            label: 'AWS',
            items: [
              {
                type: 'doc',
                id: 'Guides/Cloud Cost Savings Series/AWS/lambda',
              },
              {
                type: 'doc',
                id: 'Guides/Cloud Cost Savings Series/AWS/ebs',
              },
              {
                type: 'doc',
                id: 'Guides/Cloud Cost Savings Series/AWS/cloudwatch',
              },
              {
                type: 'doc',
                id: 'Guides/Cloud Cost Savings Series/AWS/cloudwatch',
              },
              ],
            },
          ] 
        }
      ]
    },
    {
      type: 'category',
      label: 'Cloud Providers',
      items: [
        {
          type: 'doc',
          id: 'Cloud Providers/aws',
        },
        {
          type: 'doc',
          id: 'Cloud Providers/azure',
        },
        {
          type: 'doc',
          id: 'Cloud Providers/digital-ocean',
        },
        {
          type: 'doc',
          id: 'Cloud Providers/gcp',
        },
        {
          type: 'doc',
          id: 'Cloud Providers/ovh',
        },
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        {
          type: 'doc',
          id: 'Contributing/contribute',
        }
      ],
    },
    {
      type: 'doc',
      id: 'FAQ/faq',
    },
  ]  
};

module.exports = sidebars;
